### ISSUE TITLE
API update

### ISSUE THREAD

**Issue by LittleBeannie** [Merck/simtrial#25]
In `simtrial`, most of the function/variable/argument name follows the camel case (e.g., the `enrollRates` argument in the `simfix` function). In modern package development, people follow snake case. For example,  `enrollRates` should be `enroll_rate` in snake case. The differences between snake case and camal are summarized in https://www.freecodecamp.org/news/snake-case-vs-camel-case-vs-pascal-case-vs-kebab-case-whats-the-difference/. 

**Function name update:** 
- [x] `fixedBlockRand` -> `randomize_by_fixed_block` @lili-ling-msd, see #32 
- [x] `cutData` -> `cut_data_by_date` @XintongLi2023, see #33
- [x] `cutDataAtCount` -> `cut_data_by_event` @XintongLi2023, see #34
- [x] `getCutDateForCount` -> `get_cut_date_by_event` @XintongLi2023, see #35
- [x] `rpwenroll` -> `rpw_enroll` @lili-ling-msd, see #36
- [x]  `pwexpfit` -> `fit_pwexp` @lili-ling-msd, see #37
- [x] `pMaxCombo` -> `pvalue_maxcombo` @lili-ling-msd, see #38
- [x] `tenFH` -> `wlr` @lili-ling-msd, see #39
- [x] `tenFHcorr` ->  will be merged into `wlr` given the `rg` @LittleBeannie 
- [x] `tensurv` -> `counting_process` @lili-ling-msd, see #40
- [x] `wMB` -> `mb_weight` @XintongLi2023 , see #41
- [x] `simPWSurv` -> `sim_pw_surv`? @XintongLi2023, see #42
- [x] `simfix` -> `sim_fixed_n`? @XintongLi2023, see #43

**Arguments to be updated:**
- [x] `enrollRates` -> `enroll_rate` @lili-ling-msd, see #44
- [x] `failRates` -> `fail_rate`, @XintongLi2023, see #45
- [x] `failRate` -> `fail_rate` @XintongLi2023, see #45
- [x] `dropoutRates` -> `dropout_rate` @lili-ling-msd, see #46
- [x] `dropoutRate` -> `dropout_rate` @lili-ling-msd, see #46
- [x] `sampleSize` -> `sample_size` @XintongLi2023 , see #47
- [x] `targetEvents` -> `target_event` @lili-ling-msd, see #48
- [x] `timingType` -> `timing_type` @XintongLi2023 , see #49
- [x] `rg` -> `rho_gamma` @lili-ling-msd, see #50
- [x] `strata` -> `stratum` @XintongLi2023, see #51
- [x] `Stratum` -> `stratum` @XintongLi2023, see #51
- [x] `Treatment` -> `treatment` @lili-ling-msd, see #52
- [x] `"Control"` -> `"control"` @lili-ling-msd, see #52
- [x] `"Experimental"` -> `"experimental"` @lili-ling-msd, see #52
- [x] `nsim` -> `n_sim` @XintongLi2023, see #53
- [x] `cutDate` -> `cut_date` @lili-ling-msd, see #54
- [x] `count` -> `event` in `cutDataAtCount` and `getCutDateForCount` @XintongLi2023, see #55
- [x] `dummyvar` -> `dummy_var` in `pMaxCombo` @lili-ling-msd, see #56
- [x] `Z` -> `z` in `pMaxCombo` @XintongLi2023 , see #57
- [x] `Srv` -> `srv` in `pwexpfit` @lili-ling-msd, see #58
- [x] `returnVariance` -> `return_variance` in `tenFH` @XintongLi2023 , see #59
- [x] `txval` -> `arm` in `tensurv` @lili-ling-msd, see #60
- [x] `wmax` -> `w_max` in `wMB` @XintongLi2023 , see #61

**Output variable names to be updated in `tensurv`:**

- [x] `Stratum` -> `stratum` (assigned to Xintong, same as #51 )
- [x] `events` -> `n_event_tol` @LittleBeannie, see #28 
- [x] `txevents` ->  `n_event_trt` @LittleBeannie, see #28 
- [x] `atrisk` -> `n_risk_tol`  @LittleBeannie, see #28 
- [x] `txatrisk` -> `n_risk_trt`  @LittleBeannie, see #28 
- [x] `S` -> `s` @LittleBeannie 
- [x] `OminusE` -> `o_minus_e`  @LittleBeannie, see #28 
- [x] `Var` ->  `var_o_minus_e` @LittleBeannie, see #28 

![image](https://user-images.githubusercontent.com/43153957/214648642-4d6ea168-bad2-4c2c-80db-d6e3e8a701c0.png)

**Output variable names to be updated in `tenFH`, `tenFH`:**

- [x] `Z` -> `z` (assigned to Xintong, same as #57)
- [x] `V1` -> `v1`  @LittleBeannie 
![image](https://user-images.githubusercontent.com/43153957/214646929-2b31f319-b33f-48bc-8f57-2e024f4f6fc7.png)
![image](https://user-images.githubusercontent.com/43153957/214647211-060a46cf-ea49-44ca-ad74-7b2e397bb84d.png)

**Output variable names to be updated in `cutData`, `CutDataAtCount`:**

- [x] `Stratum` -> `stratum` (assigned to Xintong, same as #51 )
- [x] `Treatment` -> `treatment` @LittleBeannie 
![image](https://user-images.githubusercontent.com/43153957/214610999-45e4e247-cad1-4b83-bc24-fdcc02890975.png)

**Output of `pwexpfit`:**

- [x] `TTOT` -> `ttot` @LittleBeannie, see #28 
- [x] `events` -> `event` @LittleBeannie, see #28 

![image](https://user-images.githubusercontent.com/43153957/214629039-274e39b9-d376-4234-9e9f-7e1844703886.png)

**Output of `simfix`:**

- [x] `Events` -> `event` @LittleBeannie 
- [x] `lnhr` -> `ln_hr` @LittleBeannie 
- [x] `Duration` -> `duration` @LittleBeannie 
- [x] `Sim` -> `sim` @LittleBeannie 
![image](https://user-images.githubusercontent.com/43153957/214637774-7762a1c2-6ea1-4f79-bb31-3a34e972ba28.png)

**Output of `simfix2simPWSurv` and `simPWSurv`:**

- [x] `Staratum` -> `stratum` (assigned to Xintong, same as #51)
- [x] `Treatment` -> `treatment` @LittleBeannie 
- [x] `enrollTime` -> `enroll_time` (assigned to Lili, same as #44)
- [x] `failTime` -> `fail_time` (assigned to Xintong, same as #45)
- [x] `dropoutTime` -> `dropout_time` (assigned to Lili, same as #46)
![image](https://user-images.githubusercontent.com/43153957/214645947-03063480-1af7-4338-ae3c-58cdcd6e745c.png)
![image](https://user-images.githubusercontent.com/43153957/214646201-e9e6419c-3551-4acf-a9eb-2424abe0e452.png)

**Comment by LittleBeannie** [comment]
**Function name update:**

Part 1: cut function:
- [ ] `cutData` -> `cut_data_at_date`?
- [ ] `cutDataAtCount` -> `cut_data_at_event`?
- [ ] `getCutDateForCount` -> `get_cut_date_for_event`?

Part 2: functions related to distributions (like r,p,q,d)
- `rpwenroll` -> `rpwe_enroll`, `rpwexp_enroll`?
- `rpwexp`
- `pwexpfit` -> ?

Part 3: functions to calculate statistics
- [ ] `pMaxCombo` -> `calc_pvalue_maxcombo`
- [ ] `tenFH` -> `calc_fh_z`
- [ ] `tenFHcorr` -> `calc_maxcombo_z`
- [ ] `tensurv` -> ?
- [ ] `wMB` -> `calc_wlr_z`

Part 4: high-level functions
- [ ] `simPWSurv` -> `simu_pw_surv`?
- [ ] `simfix` -> `simu_under_fixed_sample_size`?

**Comment by LittleBeannie** [comment]
**Arguments to be updated:**
- [ ] `enrollRates` -> `enroll_rate`
- [ ] `failRates` -> `fail_rate`, 
- [ ] `failRate` -> `fail_rate`
- [ ] `dropoutRates` -> `dropout_rate`
- [ ] `dropoutRate` -> `dropout_rate`
- [ ] `sampleSize` -> `sample_size`
- [ ] `targetEvents` -> `target_event`
- [ ] `timingType` -> `timing_type`
- [ ] `rg` -> `rho_gamm`
- [ ] `strata` -> `stratum`,
- [ ] `Stratum` -> `stratum`
- [ ] `Treatment` -> `treatment`
- [ ] `"Control"` -> `"control"`
- [ ] `"Experimental"` -> `"Experimental"`
- [ ] 
- [ ] `nsim` -> `n_sim`
- [ ]

**Comment by nanxstats** [comment]
I'd recommend we find a more descriptive alternative for anything involving `calc_`.

Also, perhaps `simu_` is not a too common prefix.

**Comment by LittleBeannie** [comment]
> I'd recommend we find a more descriptive alternative for anything involving `calc_`.
> 
> Also, perhaps `simu_` is not a too common prefix.

Aligned! This is still in my draft and will align with Keaven & you next week for a final decision.

**Comment by LittleBeannie** [comment]
**Output variable names to be updated:**

- [ ] `Stratum` -> `stratum` in `tensurv`
- [ ] `events` -> `n_event_tol` in `tensurv`
- [ ] `txevents` ->  `n_event_trt` in `tensurv`
- [ ] `atrisk` -> `n_at_risk_tol`   in `tensurv`
- [ ] `txatrisk` -> `n_at_risk_trt` in `tensurv`
- [ ] `S` -> in `s` in `tensurv`
- [ ] `OminusE` -> `o_minus_e`  in `tensurv`
- [ ] `Var` ->  `var_o_minus_e` in `tensurv`

**Comment by LittleBeannie** [comment]
**Output variable names to be updated in `tenFH`:**

- [ ] `Var` -> `var`

**Comment by LittleBeannie** [comment]
**Output variable names to be updated in `cutData`:

- [ ] `Stratum` -> `stratum`
- [ ] `Treatment` -> `treatment`
![image](https://user-images.githubusercontent.com/43153957/214610999-45e4e247-cad1-4b83-bc24-fdcc02890975.png)

**Comment by LittleBeannie** [comment]
**Output of `pwexpfit`:**

- [ ] `TTOT` -> `ttot`
- [ ] `events` -> `event`
- [ ] `m2ll` -> ?

![image](https://user-images.githubusercontent.com/43153957/214629039-274e39b9-d376-4234-9e9f-7e1844703886.png)

**Comment by LittleBeannie** [comment]
**Output of `simfix`:**

- [ ] `Events` -> `event`
- [ ] `lnhr` -> `ln_hr`
- [ ] `Z` -> ? (better to keep the upper case? Since it is the test statistics)
- [ ] `Duration` -> `duration`
- [ ] `Sim` -> `sim`
![image](https://user-images.githubusercontent.com/43153957/214637774-7762a1c2-6ea1-4f79-bb31-3a34e972ba28.png)

**Comment by LittleBeannie** [comment]
**Output of `simfix2simPWSurv`:**

- [ ] `Staratum` -> `stratum`
- [ ] Treatment` -> `treatment`
![image](https://user-images.githubusercontent.com/43153957/214645947-03063480-1af7-4338-ae3c-58cdcd6e745c.png)

**Comment by LittleBeannie** [comment]
Hi @nanxstats , should the output variable name follows the snake case? 

Some of the functions are "baby" functions and they are called in "patient" functions. Since they are called internally, is it better to keep all output variable names in the snake case?

**Comment by nanxstats** [comment]
@LittleBeannie Yes, I think it would be the best if we can keep the style **consistent**. The code linter will detect all style violations, regardless if they are from internal or exported functions. I know it could be a lot of refactoring work, though!
